name: fcare

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fcare
      POSTGRES_PASSWORD: fcare
      POSTGRES_DB: fcare
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U fcare -d fcare']
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI

  api:
    profiles: ['app']
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    environment:
      DATABASE_URL: postgresql://fcare:fcare@postgres:5432/fcare?schema=public
      REDIS_URL: redis://redis:6379
      API_PORT: 3001
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    profiles: ['app']
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  postgres-data:
  redis-data:
